### ISSUE TITLE
main.cpp:16:15: error: '::main' must return 'int'

### ISSUE THREAD

**Issue by fanfan411** [clchan000/Real-time-Multiple-QR-codes-Detection-Segmenation-and-Decoding#1]
Hello, when we compile your code, the following problem occurs
![error](https://user-images.githubusercontent.com/105193915/167353438-135eb8f3-c052-4efc-8aae-c082fa2a3a6d.png)

The specific error is like this, how can I solve it?
thank you very much!

**Comment by clchan000** [comment]
Hello. It seems because of void return from main. I added a return value to the source, so please check it.
